# Dockerfile for building image that contains software stack provisioned by Ansible.
#
# Version  1.0
#


# pull base image
FROM williamyeh/ansible:centos6-onbuild

MAINTAINER William Yeh <william.pjyeh@gmail.com>


#
# build phase
#

RUN echo "===> Installing the missing "tar" utility for Docker image..."  && \
    yum -y install tar which

ENV REQUIREMENTS  test-requirements.yml
ENV PLAYBOOK      test.yml
RUN ansible-playbook-wrapper -vvv



#
# test phase
#

RUN echo "===> Installing curl for testing purpose..."  && \
    yum -y install curl


VOLUME ["/data"]
ENV    RESULT     /data/result-centos6

CMD \
    service elasticsearch start  &&  sleep 30  && \
    curl --retry 5 --retry-max-time 120  http://localhost:9200/  -v -o $RESULT