# Dockerfile for building image that contains software stack provisioned by Ansible.
#
# Version  1.0
#


# pull base image
FROM williamyeh/ansible:centos7-onbuild

MAINTAINER William Yeh <william.pjyeh@gmail.com>


#
# build phase
#

RUN echo "===> Installing the missing "tar" utility for Docker image..."  && \
    yum -y install tar which

ENV REQUIREMENTS  test-requirements.yml
ENV PLAYBOOK      test.yml
RUN ansible-playbook-wrapper --extra-vars "elasticsearch_use_service=False" -vvv



#
# test phase
#

RUN echo "===> Installing curl for testing purpose..."  && \
    yum -y install curl

COPY test/gen-url.sh  /


#VOLUME ["/data"]
#ENV    RESULT     /data/result-centos7

CMD  /usr/share/elasticsearch/bin/elasticsearch
