# Dockerfile for building image that contains software stack provisioned by Ansible.
#
# Version  1.0
#


# pull base image
FROM williamyeh/ansible:ubuntu14.04-onbuild

MAINTAINER William Yeh <william.pjyeh@gmail.com>


#
# build phase
#

ENV REQUIREMENTS  test-requirements.yml
ENV PLAYBOOK      test.yml
RUN ansible-playbook-wrapper



#
# test phase
#

RUN echo "===> Installing curl for testing purpose..."  && \
    DEBIAN_FRONTEND=noninteractive  \
    apt-get install -y -f curl

COPY test/gen-url.sh  /


VOLUME ["/data"]
ENV    RESULT     /data/result-ubuntu14.04

CMD  service elasticsearch start  &&  sleep 30  &&  /gen-url.sh > url  &&  cat url | xargs -t -n 1 curl -v -o $RESULT
