# Dockerfile for building image that contains software stack provisioned by Ansible.
#
# Version  1.0
#


# pull base image
FROM williamyeh/ansible:debian7-onbuild

MAINTAINER William Yeh <william.pjyeh@gmail.com>


#
# build phase
#

ENV REQUIREMENTS  test-requirements.yml
ENV PLAYBOOK      test.yml
RUN ansible-playbook-wrapper -vvv



#
# test phase
#

RUN echo "===> Installing curl for testing purpose..."  && \
    DEBIAN_FRONTEND=noninteractive  \
    apt-get install -y -f curl


VOLUME ["/data"]
ENV    RESULT     /data/result-debian7

CMD \
    /usr/share/elasticsearch/bin/elasticsearch -d  &&  sleep 30  && \
    curl --retry 5 --retry-max-time 120  http://localhost:9200/  -v -o $RESULT