sudo: true
services:
    - docker

before_install:
    - docker info
    - docker version

    - docker build  -f test/Dockerfile-ubuntu14.04  -t es_trusty   .
    - docker build  -f test/Dockerfile-ubuntu12.04  -t es_precise  .
    - docker build  -f test/Dockerfile-debian8      -t es_jessie   .
    - docker build  -f test/Dockerfile-debian7      -t es_wheezy   .
    - docker build  -f test/Dockerfile-centos7      -t es_centos7  .
    - docker build  -f test/Dockerfile-centos6      -t es_centos6  .

script:
    - docker run  -v $(pwd):/data  es_trusty
    - docker run  -v $(pwd):/data  es_precise
    - docker run  -v $(pwd):/data  es_jessie
    - docker run  -v $(pwd):/data  es_wheezy
    - docker run  -v $(pwd):/data  es_centos7
    - docker run  -v $(pwd):/data  es_centos6

    - echo "==> Validating the test results..."
    - grep 'lucene_version'   result-ubuntu14.04
    - grep 'lucene_version'   result-ubuntu12.04
    - grep 'lucene_version'   result-debian8
    - grep 'lucene_version'   result-debian7
    - grep 'lucene_version'   result-centos7
    - grep 'lucene_version'   result-centos6


notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/