- hosts: all
  become: True

  roles:
    - williamyeh.oracle-java

  tasks:
    - include: 'tasks/main.yml'
  handlers:
    - include: 'handlers/main.yml'
  vars_files:
    - 'defaults/main.yml'

  vars:
    elasticsearch_version: 2.1.1
    #elasticsearch_version: 1.7.3

    # copy verbatim
    #elasticsearch_conf_copy: "files/elasticsearch.yml"

    # copy through Ansible's template system
    #elasticsearch_conf_template: "templates/elasticsearch.yml.j2"


    elasticsearch_heap_size: 200m