---
# file: tasks/memory.yml
# Set JVM memory for Elasticsearch.
#

- name: patch to use G1GC, if necessary
  sudo: True
  lineinfile: >
    dest="{{ elasticsearch_include }}" 
    regexp='^(.+)-XX:\+UseParNewGC"' 
    line="\\1-XX:+UseG1GC\"" 
    backrefs=yes backup=yes
  when: elasticsearch_use_g1gc
  notify: restart elasticsearch

- name: patch to use G1GC, if necessary
  sudo: True
  lineinfile:
    dest="{{ elasticsearch_include }}"
    regexp='^(.+)-XX:\+UseConcMarkSweepGC"'
    line="\\1-XX:+UseG1GC\""
    backrefs=yes backup=yes
  when: elasticsearch_use_g1gc
  notify: restart elasticsearch



#- name: set ES_HEAP_SIZE, if necessary
#  sudo: True
#  lineinfile: >
#    dest=/etc/environment 
#    regexp='^ES_HEAP_SIZE=(.+)' 
#    line="ES_HEAP_SIZE={{ elasticsearch_heap_size }}"
#  when: elasticsearch_heap_size is defined
#  notify: restart elasticsearch

- name: set ES_HEAP_SIZE in INIT script, if necessary
  sudo: True
  lineinfile: >
    dest=/etc/init.d/elasticsearch
    regexp='^export ES_HEAP_SIZE' 
    line="export ES_HEAP_SIZE={{ elasticsearch_heap_size }}"
  when: elasticsearch_heap_size is defined
  notify: restart elasticsearch
  ignore_errors: true


- name: set ES_HEAP_SIZE in /etc/default/elasticsearch, if necessary
  sudo: True
  lineinfile: >
    dest=/etc/default/elasticsearch
    regexp='^.?ES_HEAP_SIZE=' 
    line="ES_HEAP_SIZE={{ elasticsearch_heap_size }}"
  when: elasticsearch_heap_size is defined
  notify: restart elasticsearch
  ignore_errors: true


# useful in CentOS 7 systemd
- name: set ES_HEAP_SIZE in /etc/sysconfig/elasticsearch, if necessary
  sudo: True
  lineinfile: >
    dest=/etc/sysconfig/elasticsearch
    regexp='^.?ES_HEAP_SIZE=' 
    line="ES_HEAP_SIZE={{ elasticsearch_heap_size }}"
  when: elasticsearch_heap_size is defined
  notify: restart elasticsearch
  ignore_errors: true
