---
# file: tasks/set-role-variables.yml
# set necessary role variables.
#

- name: set elasticsearch_use_service = True, if not defined
  set_fact:
    elasticsearch_use_service: True
  when: elasticsearch_use_service is not defined
