---
# file: tasks/use-deb.yml
#
# Configure Elasticsearch from DEB file.  
#
#

- name: download DEB file
  get_url: url="https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-{{ elasticsearch_version }}.deb"  dest=/tmp/es.deb

- name: install from DEB
  apt: deb=/tmp/es.deb


- name: set INIT status
  service: name=elasticsearch enabled=yes

#- name: set INIT status (SysV style)
#  shell: update-rc.d elasticsearch defaults
