---
# file: tasks/use-deb.yml
#
# Configure Elasticsearch from DEB file.  
#
#

- name: download DEB file
  get_url: url="https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-{{ elasticsearch_version }}.deb"  dest=/tmp/es.deb

- name: install from DEB
  sudo: True
  apt: deb=/tmp/es.deb



- name: set INIT status (SysV style)
  sudo: True
  shell: update-rc.d elasticsearch defaults
