---
# file: tasks/use-rpm.yml
#
# Configure Elasticsearch from RPM file.  
#
# @see http://docs.fluentd.org/articles/install-by-rpm
# @see http://toolbelt.treasuredata.com/sh/install-redhat-td-agent2.sh
#


- name: install libselinux-python binary for Ansible to work 
  yum: name=libselinux-python state=present


- name: download and install from RPM
  yum:
    name: "https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-{{ elasticsearch_version }}.noarch.rpm"
    state: present


- name: set INIT status
  service: name=elasticsearch enabled=yes

#- name: set INIT status (SysV style)
#  action: shell chkconfig --add elasticsearch
#  action: shell chkconfig --level 345 elasticsearch on
