---
# file: handlers/main.yml
#

- name: restart elasticsearch
  service: name=elasticsearch state=restarted
  when: elasticsearch_use_service|bool

- name: stop elasticsearch
  service: name=elasticsearch state=stopped
  when: elasticsearch_use_service|bool
